# Python numpy

In [1]:
'''
Lo primero es comprobar que tenemos instalado nmumpy y que lo podemos importar correctamente.
La ejecución de este bloque de código nos debe mostrar el array [1,2,3,4,5]
'''
import numpy as np

# Definición de un nuevo 'ndarray', de ahora en adelante lo llamaremos simplemente 'array'
test = np.array([1, 2, 3, 4, 5])
print(test)

[1 2 3 4 5]


### Primeros pasos

In [ ]:
# Para iniciar una array de numpy llamamos a la función np.array()
a = np.array([1,2,3,4,5]) #siempre los valores tienen que ser del mismo tipo de dato
print(a)


[1 2 3 4 5]


In [ ]:
# Para inicializar una array de dim 2 podemos pasar una lista de listas
b = np.array([[1,2,3], [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Podemos anidar más listas para crear arrays de dim 3 o mas
c = np.array([
    [
        [1,2,3], [4,5,6]
        ], [
            [1,2,3], [4,5,6]
            ]
        
        ])
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
# Obtener la dimensión de un array
a.ndim

1

In [ ]:
# Obtener la dimensión del array b
b.ndim  

2

In [ ]:
# Obtener la dimensión del array c
c.ndim

3

In [ ]:
# vamos a crear un array de 3 dimensiones
d = np.array(
    [[[1,4,7], [2,9,7], [1,3,0], [9,6,9]],
    [[2,3,4], [4,5,5], [1,2,2], [9,3,8]]]

    
    
    )
print(d)
print(d.ndim)

[[[1 4 7]
  [2 9 7]
  [1 3 0]
  [9 6 9]]

 [[2 3 4]
  [4 5 5]
  [1 2 2]
  [9 3 8]]]
3


In [ ]:
# El shape de un array es una tupla que indica el tamaño de cada dimensión
print(a)
print(a.shape)


[1 2 3 4 5]
(5,)


In [ ]:
print(b)
print(b.shape) # 2 dimension, cada lista tiene 3 elementos

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
print(c)
print(c.shape) # primer corchete engloba 2 elementos, segundo corchete tiene 2 elementos (todos los elementos de la dimension tiene que se los mismos), 
#dentro de cada elemento son 3 numeros

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)


In [ ]:
print(d)
print(d.shape) # 1º corchete 2, 2º corchete tiene 4 listas, 3º cada lista tiene 3 numeros

[[[1 4 7]
  [2 9 7]
  [1 3 0]
  [9 6 9]]

 [[2 3 4]
  [4 5 5]
  [1 2 2]
  [9 3 8]]]
(2, 4, 3)


In [ ]:
# Obtener el tipo de dato de un array
a.dtype #int64 = 8 bits, 64 bits

dtype('int32')

Representación de un byte en binario -> 1010

El tipo int16 puede representar un número entero de 16 bits (2 bytes)(-32.768 a 32.767)
El tipo int32 puede representar un número entero de 32 bits (4 bytes)(-2.147.483.648 a 2.147.483.647)
El tipo int64 puede representar un número entero de 64 bits (8 bytes)(-9.223.372.036.854.775.808 a 92.23.372.036.854.775.807)

El tipo float32 puede representar un número real de 32 bits (4 bytes)(-3.4028235e+38 a 3.4028235e+38)
El tipo float64 puede representar un número real de 64 bits (8 bytes)(-1.7976931348623157e+308 a 1.7976931348623157e+308)

In [ ]:
'''
Define un array de dim 2 y de tipo int16
'''
a16 = np.array([[1,2,3],[4,5,6]], dtype = np.int16)
print(a16)
print(a16.dtype)

[[1 2 3]
 [4 5 6]]
int16


In [ ]:
# EL tipo de dato no es capaz de manejar valores fuera de su rango ( 32,768) por lo que se produce un overflow e introduce basura
b16 = np.array([[1,2,3], [4,5,64000]], dtype = np.int32)
print(b16)

[[    1     2     3]
 [    4     5 64000]]


In [ ]:
# Redifiinar el tipo de un array
'''
Convertir el array a16 a tipo int32
'''
a32 = a16.astype(np.int32)
print(a16.dtype)
print(a16)
print(a32.dtype)
print(a32)

int16
[[1 2 3]
 [4 5 6]]
int32
[[1 2 3]
 [4 5 6]]


In [ ]:
# Saber cuanto ocupa en memoria un array
# utilizando el array de ejemplo anterior a16

'''
Obtener cuanto ocupa en memoria un elemento del array a16
'''
print('Array a16\n', a16)
print(a16.itemsize, 'bytes')

# numero de elemento que tiene el array
print('Elementos array a16:', a16.size)
print('Tamaño de cada elemento delarray a16:', a16.itemsize, 'bytes')
print('Tamaño total del array a16:', a16.size * a16.itemsize, 'bytes' )

Array a16
 [[1 2 3]
 [4 5 6]]
2 bytes
Elementos array a16: 6
Tamaño de cada elemento delarray a16: 2 bytes
Tamaño total del array a16: 12 bytes


In [ ]:
'''
Obtener cuanto ocupa en memoria un elemento del array a32
'''
print('Array a32\n', a32)


# numero de elemento que tiene el array
print('Elementos array a16:', a32.size)
print('Tamaño de cada elemento delarray a16:', a32.itemsize, 'bytes')
print('Tamaño total del array a16:', a32.size * a32.itemsize, 'bytes' )

Array a32
 [[1 2 3]
 [4 5 6]]
Elementos array a16: 6
Tamaño de cada elemento delarray a16: 4 bytes
Tamaño total del array a16: 24 bytes


In [ ]:
# Otra forma de inicializar un array (range)
# ejemplo de range
ejemplo1 = list(range(10))
print(ejemplo1)

for i in range(10):
    print(i)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
0
1
2
3
4
5
6
7
8
9


In [ ]:
# Inicializar array con range. El array debe tener 10 elementos

a = np.array(range(10))
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
''' 
Inicializa un array con arange. El array debe tener 10 elementos
'''
b = np.arange(10) # solo se puede hacer 1 dimensión
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
''' 
Inicializa un array con arange Desde 10 hasta 10 con paso 2
'''
c = np.arange(10,20,2)
print(c)

[10 12 14 16 18]


Ejercicios

In [ ]:
'''
Define el array 'a' del 1 al 10
'''
a = np.arange(1,11)
print(a)
'''
Imprime la dimension del array y el shape
'''
print(a.ndim)
print(a.shape)

[ 1  2  3  4  5  6  7  8  9 10]
1
(10,)


In [ ]:
''' 
Define de un array 'b' de dimensiones 2x3 a partir de listas anidadas
'''

b = np.array ([[1,2,3], [4,5,6]])
print(b)
print(b.shape)


[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
'''
Define un array 'c'  de dim 2x2x3 a partir de una lista de listas anidadas 
'''
c = np.array([
    [[1,2,3],[4,5,6]]
    ,[[7,8,9],[10,11,12]]
    ])
print(c)
'''
Imprime el número total de elementos del array y el shape
'''
print(c.size)
print(c.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
12
(2, 2, 3)


## Accediendo y Modificando elementos de un array

In [ ]:
# Array de 2x5
f = np.array([[1,2,3,8,7],[4,5,6,2,9]])
print(f)

[[1 2 3 8 7]
 [4 5 6 2 9]]


Obtener un elemento de un array

In [ ]:
# Obtener un elemento concreto de un array [rows,columns]
# obtener el elemento 6 del array f
print(f[1,2])
# obtener el elemento 8 del array f
print(f[0,3])

6
8


Obtener una fila completa de un array

In [ ]:
# Para obtener una fila completa utilizamos la notación ':' como en la listas
ejemplo = [1,2,3,4,5,6,7,8]
ejemplo[2:] #hasta el final
print(f)
f[1,:]

[[1 2 3 8 7]
 [4 5 6 2 9]]


array([4, 5, 6, 2, 9])

Obtener una columna completa de un array

In [ ]:
# define un array 'f' de dimensiones 4x5
# Obtener la columna 3 de array f
f = np.array([[1,2,3,8,7],[4,5,6,2,9],[1,2,3,8,7],[4,5,6,2,9]])
print(f)
f[:,2]

[[1 2 3 8 7]
 [4 5 6 2 9]
 [1 2 3 8 7]
 [4 5 6 2 9]]


array([3, 6, 3, 6])

Otras formas de acceder a los elementos de un array

In [ ]:
# Para acceder de una forma un poco más avanzada se utiliza [inicio: final: paso]
f[0,1:4:2]

array([2, 8])

In [ ]:
# Obtener las filas pares
f[::2,:]
#f[filas, columnas]

array([[1, 2, 3, 8, 7],
       [1, 2, 3, 8, 7]])

In [ ]:
# Recorrer con paso negativo
f_invertido = f[::-1,:] # Invertir el array
print(f_invertido)


[[4 5 6 2 9]
 [1 2 3 8 7]
 [4 5 6 2 9]
 [1 2 3 8 7]]


In [ ]:
# Definir un array de 3x3x2
g = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,20,30],[40,50,60],[70,80,90]]])
print(g)
#acceder elemento 50
print(g[1,1,1])
# acceder a la fila 2 del elemento 1
print(g[1,2,:])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]
50
[70 80 90]


Actualizar un elemento de un array

In [ ]:
# Podemos actualizar la información de un array igual que seleccionando un elemento e igulandolo con un nuevo valor
# Para este ejemplo vamos a utilizar el array 'g' de 3x3x2
h = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,20,30],[40,50,60],[70,80,90]]])
print(h)
print()
# Establecer el elemento 50 a 500
h[1,1,1,] = 500

print(h)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]

[[[  1   2   3]
  [  4   5   6]
  [  7   8   9]]

 [[ 10  20  30]
  [ 40 500  60]
  [ 70  80  90]]]


In [ ]:
# Podemos actualizar una fila completa
i = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,20,30],[40,50,60],[70,80,90]]])
print(i)
print()

# establecer la fila 0 del elemento 1 a 0
i[1,0,:] = 0
print(i)
print()

# establecer la fila 0 del elemento 1 a 1,2,3
i[1,0,:] = [1,2,3]
print(i)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 0  0  0]
  [40 50 60]
  [70 80 90]]]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 1  2  3]
  [40 50 60]
  [70 80 90]]]


In [ ]:
# Definir un array de 3x3x2 
j = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,20,30],[40,50,60],[70,80,90]]])
print(j)
print()
# Establecer la ultima columna de todos los elementos a 0
j[:,:,2] = 0 # o j[:,:,-1]
print(j)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]

[[[ 1  2  0]
  [ 4  5  0]
  [ 7  8  0]]

 [[10 20  0]
  [40 50  0]
  [70 80  0]]]


In [ ]:
# Definir un array de 3x3x2 
k = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,20,30],[40,50,60],[70,80,90]]])
print(k)
print()
# Establecer la ultima columna de todos los elementos a 0
k[:,:,2] = [1,2,3] # o k[:,:,-1]
print(k)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]

[[[ 1  2  1]
  [ 4  5  2]
  [ 7  8  3]]

 [[10 20  1]
  [40 50  2]
  [70 80  3]]]


Ejercicios

In [ ]:
'''
Define un array 's' de tamaño 10 y selecciona el valor de la posición 5
'''
s = np.random.randint(0,10, size= 10)
print(s)
s[4] # 23



[4 7 5 9 0 6 8 8 8 6]


0

In [ ]:
'''
Sobre el array s, selecciona el valor 5
'''

s[4] = 5

print(s)

[4 7 5 9 5 6 8 8 8 6]


In [ ]:
'''
Define el array 's' de tamaño 25 y selecciona los valores pares
'''
s = np.random.randint(0,100, size= 25)
print(s)

s[s%2==0]

[86 48 22 31  3 88 74 87  8 82 40 92 28 32 55 13  4 63 54 14 61 65 98 72
 18]


array([86, 48, 22, 88, 74,  8, 82, 40, 92, 28, 32,  4, 54, 14, 98, 72, 18])

In [ ]:
'''
Define el array 's' de tamaño 25 y selecciona los valores impares
'''

s = np.random.randint(0,100, size= 25)
print(s)

s[s%2!=0]

[70 83  5 84  5 74 88 96 67 53 49 95 93 72 70 52 89 82 43 82 99  8 17 57
 58]


array([83,  5,  5, 67, 53, 49, 95, 93, 89, 43, 99, 17, 57])

In [ ]:
'''
Sobre el array s, selecciona el uĺltimo valor
'''

print(s)
s[-1]

[70 83  5 84  5 74 88 96 67 53 49 95 93 72 70 52 89 82 43 82 99  8 17 57
 58]


58

In [ ]:
"""
Define el array 's' de tamaño 20 e invierte el orden de los valores
"""
s = np.random.randint(0,100, size= 20)
print(s)

s_invertido = s[::-1]
print(s_invertido)



[ 0 71  7 61 76 51 85 73 92 38 74 95 30 16 44 26 85 94 94 27]
[27 94 94 85 26 44 16 30 95 74 38 92 73 85 51 76 61  7 71  0]


In [ ]:
'''
Define un array s2 multidimensional de tamaño 2x2 y selecciona el valor de la segunda fila y la segunda columna
'''
s2 = np.array([[1,2],[3,4]])
print(s2)
print(s2[1,:])
print(s2[:,1])


[[1 2]
 [3 4]]
[3 4]
[2 4]


In [ ]:
'''
Define el array:
[
[[1, 2], [3, 4]]
[[5, 6], [7, 8]]
]
y selecciona el valor de la segunda dimension, primera fila, segunda columna
'''
s2 = np.array([
[[1, 2], [3, 4]],
[[5, 6], [7, 8]]
])
print(s2)

print(s2[1,0,1])


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
6


In [ ]:
'''
Define un array s4 de tamaño 4x4x3 y establece los números centrales a 99
'''
s4 = np.array([
[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],
[[20,21,22],[23,24,25],[26,27,28],[29,30,31]],
[[32,33,34],[35,36,37],[38,39,40], [41,42,43]],
[[60,61,62],[63,64,65],[66,67,68],[69,70,71]]

])

print(s4.shape)

s4[:,:,1] = 99
print(s4)

(4, 4, 3)
[[[ 1 99  3]
  [ 4 99  6]
  [ 7 99  9]
  [10 99 12]]

 [[20 99 22]
  [23 99 25]
  [26 99 28]
  [29 99 31]]

 [[32 99 34]
  [35 99 37]
  [38 99 40]
  [41 99 43]]

 [[60 99 62]
  [63 99 65]
  [66 99 68]
  [69 99 71]]]


In [ ]:
'''
Define un array s4 de tamaño 4x4x3 y establece los números centrales a (0,1), (2,3), (4,5), (6,7)
'''
s4 = np.array([
[[1,2,3],[4,5,6],[7,8,9],[10,11,12]], # matriz 0
[[20,21,22],[23,24,25],[26,27,28],[29,30,31]], #matriz 1
[[32,33,34],[35,36,37],[38,39,40], [41,42,43]], # matriz 2
[[60,61,62],[63,64,65],[66,67,68],[69,70,71]] # matriz 3

])

s4[0,1:3,1] = (0,1) # [matriz 0, fila 1 (= 4,5,6) : 3?, columna 1]
s4[1,1:3,1] = (2,3)
s4[2,1:3,1] = (4,5)
s4[3,1:3,1] = (6,7)
#s4[0,:,1] = [0,1,2,3]
#s4[1,:,1] = [4,5,6,7]
#s4[2,:,1] = [0,1,2,3]
#s4[3,:,1] = [4,5,6,7]
print(s4)

[[[ 1  2  3]
  [ 4  0  6]
  [ 7  1  9]
  [10 11 12]]

 [[20 21 22]
  [23  2 25]
  [26  3 28]
  [29 30 31]]

 [[32 33 34]
  [35  4 37]
  [38  5 40]
  [41 42 43]]

 [[60 61 62]
  [63  6 65]
  [66  7 68]
  [69 70 71]]]


## Inicializando diferentes tipos de arrays

Matriz de ceros

In [ ]:
# Definir una matriz completa de 0 de tamaño 5x3
np.zeros((5,3)) #una tupla

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# Definir una matriz completa de 0 de tipo int32 de tamaño 5x3
np.zeros((5,3), dtype=np.int32) 

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
# POdemos generar una matriz  de zeros con una shape(2,3,4)
np.zeros((2,3,4)) # una tupla

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
# Definir una matriz de tamaño 5x3
l = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(l)
print(l.dtype)
#Definir una matriz de 0 del shape de l
print(np.zeros(l.shape))
# Otra forma de hacerlo es con la función zeros_like. Esta respeta el tipo de dato de la matriz original
print(np.zeros_like(l)) #int32


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
int32
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


Matriz de unos

In [ ]:
# Definir una matriz de 1 de tamaño 5x3
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Definir una matriz de 1 de tamaño 5x3 de tipo int32
np.ones((5,3), dtype=np.int32)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

Matriz de valores concretos

In [ ]:
# Define una matriz de tamaño 5x3 con valores = 50
np.full((5,3), 50) # array 2d

array([[50, 50, 50],
       [50, 50, 50],
       [50, 50, 50],
       [50, 50, 50],
       [50, 50, 50]])

In [ ]:
# # Define una matriz de tamaño 5x3 con valores = 50 en punto flotante
np.full((5,3), 50, dtype = np.float32)
p = np.full((5,3), 50.) # con el punto ya sabe que es un decimal

Matriz de valores concretos (full like)

In [ ]:
# Define una matriz como p (la matriz anterior)pero con valores = 75
np.full_like(p,75)

array([[75., 75., 75.],
       [75., 75., 75.],
       [75., 75., 75.],
       [75., 75., 75.],
       [75., 75., 75.]])

Matriz de números aleatorios

In [ ]:
# Atención!  Cuando creamos una matriz de numeros aleatorios no se pasa
# el shape por parametro como hemos hecho con los ceros o los ones

# Define una matriz de tamaño 5x3 con valores aleaorios
np.random.rand(5,3) # no es una tupla, son filas y columnas

array([[0.77274365, 0.87355778, 0.49366043],
       [0.8106853 , 0.03870885, 0.91754293],
       [0.20725808, 0.26945145, 0.88431275],
       [0.65955655, 0.48823386, 0.9297519 ],
       [0.61481935, 0.70306999, 0.11168817]])

In [ ]:
# Definir una matriz de 5x3 con valores comprendidos entre 0 y 100
np.random.randint(0,100, (5,3)) # np.random.randint(0,100, size= (5,3))

array([[27, 49, 50],
       [35, 55, 28],
       [52, 69, 36],
       [75, 31, 89],
       [15, 21, 77]])

In [ ]:
# Definir una matriz de 5x3 con valores comprendidos entre 100 y 200
np.random.randint(100,200, size=(5,3))

array([[127, 130, 141],
       [183, 118, 116],
       [103, 158, 104],
       [157, 197, 193],
       [114, 197, 113]])

In [ ]:
# Definir una matriz de 5x3 con valores al azar mayores que 1
np.random.rand(5,3)* 100


array([[77.51102662, 18.05691681, 53.71227045],
       [83.53961349, 72.55387436,  5.2435676 ],
       [ 5.92097806, 65.68641219, 49.68704651],
       [44.35149078, 78.07345753, 81.03826982],
       [47.63760508, 64.64914108, 87.81128241]])

Matriz identidad

In [ ]:
# Define la matriz identidad de tamaño 5x5
np.eye(5) # solo pasamos 1 parametro, pq tiene ser cuadrada 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# La matriz identidad se puede definir con la función 'identity'A
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Ejercicios

In [ ]:
'''
Define el array z de dim 1 completo de ceros
'''
z = np.zeros((1,5))
print(z)

[[0. 0. 0. 0. 0.]]


In [ ]:
'''
Define un array z de dim 8x8 completo de ceros
'''
z = np.zeros((8,8))
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
'''
Define el array 'z' completo de ceros de n dim
'''
print(z.ndim)

2


In [ ]:
'''
Define el array 'd' completo de unos de n dim
'''
d = np.ones((8,8))
print(d)
print(d.ndim)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
2


In [ ]:
'''
Define un array como el que se muestra a continuación:
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
'''

a = np.zeros((7,7))
a[1:-1,1:-1] = 1
print(a)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
'''
Define un array 'g' conun range de 0 a 10 de dim 2
'''
g = np.arange(0,10).reshape(2,5)
print(g)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
'''
Define un array 'h' con un range de 0 a 100 con un paso de 5 y una dim difrente de 1
'''
h = np.arange(0,100).reshape(2,10,5)
print(h)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]
  [75 76 77 78 79]
  [80 81 82 83 84]
  [85 86 87 88 89]
  [90 91 92 93 94]
  [95 96 97 98 99]]]


## Operaciones con arrays

operaciones básicas

In [ ]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [ ]:
# Suma
print(a + 2)

[3 4 5 6 7]


In [ ]:
# Resta
print(a - 2)

[-1  0  1  2  3]


In [ ]:
# Multiplicar
print(a*2)

[ 2  4  6  8 10]


In [ ]:
# Division
print(a/2)

[0.5 1.  1.5 2.  2.5]


In [ ]:
# Exponeciación
print(a **2)

[ 1  4  9 16 25]


Las operaciones básicas con arrays o matrices son "element wise". Esto significa que se aplican a cada elemento de la matriz.

In [ ]:
b = np.array([10, 20, 30, 40, 50])
print(b)

[10 20 30 40 50]


In [ ]:
# Podemos sumar dos arrays porque son del mismo tamaño
print(a + b)

[11 22 33 44 55]


Ejercicios

In [ ]:
'''
Define un array 'a' de tamaño 4 y un array 'b' de tamaño 4 completo de 1s. A contunuación suma los valores de ambos arrays y comprueba que los valores son correctos.
'''
a = np.random.randint(0,100, size=(4))
print(a)
b = np.ones((4))
print(b)
print(a+b)

[ 4 98 89 88]
[1. 1. 1. 1.]
[ 5. 99. 90. 89.]


In [ ]:
'''
Define un array 'a' de tamaño 4 y un array 'b' de tamaño 4 completo de 1s. A contunuación resta los valores de ambos arrays y comprueba que los valores son correctos.
'''
a = np.random.randint(0,100, size=(4))
print(a)
b = np.ones((4))
print(b)
print(a-b)

[80 42 86 78]
[1. 1. 1. 1.]
[79. 41. 85. 77.]


In [ ]:
'''
Define un array 'a' de tamaño 4 y un array 'b' de tamaño 4 completo de 2s. A contunuación multiplica o divide los valores de ambos arrays y comprueba que los valores son correctos.
'''
a = np.random.randint(0,100, size=(4))
print(a)
b = np.random.randint(0,100, size=(4))
print(b)
print(a*b)

[19 62 42 46]
[72 90 24  5]
[1368 5580 1008  230]


Álgebra lineal

numpy py permite realizar operaciones matriciales como por elemplo:
- determinante: np.linalg.det()
- inversa: np.linalg.inv()
- producto matricial: np.dot()
- diagonal: np.diag()
- inversa de una matriz: np.linalg.inv()



In [ ]:
#determinante: para saber si dos matrices son iguales
#Definir una matriz de 2x3 con valores aleatorios entre 0 y 10
a = np.random.randint(0,10, size=(2,3))
print(a)

[[9 7 0]
 [2 9 4]]


In [ ]:
b = np.random.randint(0,10, size=(3,2))
print(b)

[[3 3]
 [4 0]
 [9 3]]


In [ ]:
# esto va a dar error porque va a tratar de hacer la operación element wise
print(a*b)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [ ]:
# Para realizar la multiplicación matemática de matrices debemos usar la función 'dot' o 'matmul'
producto = np.dot(a,b)
print(producto)

[[30  5]
 [78  6]]


In [ ]:
producto = np.matmul(a,b)
print(producto)

[[30  5]
 [78  6]]


In [ ]:
producto = a @ b # igual que el dot y matmul (multiplicación matematica)
print(producto)

[[30  5]
 [78  6]]


In [ ]:
# Obtener el determinante de una matriz
a = np.identity(3)
print(a)

print('Determinante:', np.linalg.det(a))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Determinante: 1.0


In [ ]:
# Define una matriz 3x3 con valores aleatorios entre 0 y 10
b = np.random.randint(0,10, size=(3,3))
print(b)

# Obtener el determinante de una matriz


print('Determinante:', np.linalg.det(b))

[[0 6 9]
 [7 1 2]
 [7 6 5]]
Determinante: 189.00000000000003


In [ ]:
# Matriz inversa
# La matriz inversa de una matriz es igual a la matriz adjunta de su matriz traspuesta, 
# dividida por su determinante, siempre que este no sea cero.

# # Define una matriz 3x3 con valores aleatorios entre 0 y 10
c = np.random.randint(0,10, size=(3,3))
print(c)

# Obtener el determinante de una matriz
inversa = np.linalg.inv(c)
print('Matriz inversa:\n', inversa)

[[5 0 3]
 [8 7 3]
 [8 5 7]]
Matriz inversa:
 [[ 0.27868852  0.12295082 -0.17213115]
 [-0.26229508  0.09016393  0.07377049]
 [-0.13114754 -0.20491803  0.28688525]]


In [ ]:
# Matriz transpuesta
#La matriz transpuesta de una matriz es otra matriz que se obtiene al intercambiar las filas por las columnas.
d = np.random.randint(0,10, size = (3,5))
print(d)
# Obtener la matriz transpuesta
np.transpose(d)

[[3 0 9 0 2]
 [8 7 7 7 7]
 [5 7 9 5 9]]


array([[3, 8, 5],
       [0, 7, 7],
       [9, 7, 9],
       [0, 7, 5],
       [2, 7, 9]])

Más tipos de operaciones con arrays:
- **np.sum():** Suma de todos los elementos de un array
- **np.mean():** Media de todos los elementos de un array
- **np.std():** Desviación estándar de todos los elementos de un array
- **np.var():** Varianza de todos los elementos de un array
- **np.min():** Valor mínimo de todos los elementos de un array
- **np.max():** Valor máximo de todos los elementos de un array
- **np.argmin():** Indice del valor mínimo de un array
- **np.argmax():** Indice del valor máximo de un array
- **np.cumsum():** Sumatoria acumulada de un array
- **np.cumprod():** Producto acumulado de un array
- **np.flip():** Inversa de un array


In [ ]:
# Define una matriz de números aleatorios entre 0 y 10 de tamaño 3x3
e = np.random.randint(0,10,size=(3,3))
print(e)

[[1 1 7]
 [2 6 7]
 [8 6 5]]


In [ ]:
# Obtener el suma de todos los elementos de la matriz
print(np.sum(e))

43


In [ ]:
# Obtener la media de todos los elementos de la matriz
print(np.mean(e))

4.777777777777778


In [ ]:
# Obtener el valor máximo de una matriz
print(np.max(e))

In [ ]:
# Obetener el valor mínimo de una matriz
print(np.min(e))

In [ ]:
# Obtener el valor máximo de cada fila
print('máximo de cada fila:',np.max(e,axis=1))
# Obtener el valor máximo de cada columna
print('máximo de cada coluna:',np.max(e,axis=0))

In [ ]:
# Obtener el valor máximo de e[1:3,1:3]
print(e[1:3,1:3])
print(np.max(e[1:3,1:3]))

In [ ]:
# Obtener el sumatorio de cada fila
print('Sumatorio de cada fila:',np.sum(e,axis=1))
# Obtener el sumatorio de cada columna
print('Sumatorio de cada coluna:',np.sum(e,axis=0))

Ejercicios

In [ ]:
import numpy as np

In [ ]:
'''
Calcula la mediana de un array
'''
a = np.array([1,2,3,4,5,6,8,9,10])
print(a)

median = np.median(a)
print(median)

[ 1  2  3  4  5  6  8  9 10]
5.0


In [ ]:
'''
calcula la media de una matriz
'''
e = np.random.randint(0,100,size=(3,3))
print(e)
print(np.mean(e))


[[43 75 16]
 [62 63 47]
 [57 38 16]]
46.333333333333336


# Reshape

In [ ]:
matriz1 = np.array([[1, 2, 3], [4, 5, 6]])
matriz1

In [ ]:
matriz2 = matriz1.reshape(3, 2)
matriz2

In [ ]:
matriz3 = matriz1.reshape(1, 6)
matriz3

In [ ]:
# Ejemplo practico de reshape
z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
print(z)
print(z.shape)

In [ ]:
# reshape a 2 dimensiones
z = z.reshape(4, 5)
print(z)

In [ ]:
# reshape a 3 dimensiones
z.reshape(2,5,2)

#Ficheros

In [ ]:
# Crear un fichero
data = np.random.randint(0,100, size = (8,9), dtype =np.int32)
data

array([[31, 49, 93, 22, 65, 91, 88, 50, 99],
       [42, 63, 53, 12, 45, 89, 28, 57, 30],
       [31, 16, 49, 52, 98, 75, 10, 70, 88],
       [ 9, 96, 75, 98, 70, 98, 77, 49, 18],
       [40,  7, 30, 50, 95, 24, 75, 28, 43],
       [22, 65, 50, 87, 27, 26, 38, 82, 29],
       [49, 88, 89, 40, 58,  3, 87, 75, 88],
       [36, 53, 13, 79,  0, 24, 23, 79, 38]])

In [ ]:
# Guarda el array data en un csv
np.savetxt('file_data.csv', data, delimiter=';', fmt= '%d')

In [ ]:
# Carga el contenido del csv en un array llamado file_data
file_data = np.loadtxt('file_data.csv', delimiter=';', dtype=np.int32)
print(file_data)

[[31 49 93 22 65 91 88 50 99]
 [42 63 53 12 45 89 28 57 30]
 [31 16 49 52 98 75 10 70 88]
 [ 9 96 75 98 70 98 77 49 18]
 [40  7 30 50 95 24 75 28 43]
 [22 65 50 87 27 26 38 82 29]
 [49 88 89 40 58  3 87 75 88]
 [36 53 13 79  0 24 23 79 38]]


#Mascaras Booleanas

In [ ]:
print(file_data)

[[31 49 93 22 65 91 88 50 99]
 [42 63 53 12 45 89 28 57 30]
 [31 16 49 52 98 75 10 70 88]
 [ 9 96 75 98 70 98 77 49 18]
 [40  7 30 50 95 24 75 28 43]
 [22 65 50 87 27 26 38 82 29]
 [49 88 89 40 58  3 87 75 88]
 [36 53 13 79  0 24 23 79 38]]


In [ ]:
# Podemos generar una máscara booleana para filtrar los datos
file_data > 75 # array nuevo con valores booleanos que elementos cumplen con la condición

array([[False, False,  True, False, False,  True,  True, False,  True],
       [False, False, False, False, False,  True, False, False, False],
       [False, False, False, False,  True, False, False, False,  True],
       [False,  True, False,  True, False,  True,  True, False, False],
       [False, False, False, False,  True, False, False, False, False],
       [False, False, False,  True, False, False, False,  True, False],
       [False,  True,  True, False, False, False,  True, False,  True],
       [False, False, False,  True, False, False, False,  True, False]])

In [ ]:
# Esta máscara se puede aplicar a cualquier array
resultado = file_data[file_data > 75] # nos extrae exclusivamente los datos mayores de 75
print(resultado)
resultado.shape

[93 91 88 99 89 98 88 96 98 98 77 95 87 82 88 89 87 88 79 79]


(20,)

In [ ]:
mayores_de_50 = file_data > 50 # esto ya es una mascara
print(mayores_de_50)

[[False False  True False  True  True  True False  True]
 [False  True  True False False  True False  True False]
 [False False False  True  True  True False  True  True]
 [False  True  True  True  True  True  True False False]
 [False False False False  True False  True False False]
 [False  True False  True False False False  True False]
 [False  True  True False  True False  True  True  True]
 [False  True False  True False False False  True False]]


In [4]:
# Generar una lista de edades aleatorias
edades = np.array([25,48,4,15,24,52])
# Personas
personas = np.array(['Juan', 'Ana', 'Pedro', 'Luis', 'María', 'Pablo'])
print(edades)
print(personas)

# mayores de 18 años
mayores_18 = edades > 18
print(mayores_18)

# Aplicar la máscara a la lista de personas
personas_mayores_18 = personas[mayores_18]
print(personas_mayores_18)

[25 48  4 15 24 52]
['Juan' 'Ana' 'Pedro' 'Luis' 'María' 'Pablo']
[ True  True False False  True  True]
['Juan' 'Ana' 'María' 'Pablo']


In [ ]:
# Tambien podemos ver si alguno de los elementos cumple con la condición
print(np.any(file_data > 75))


True


In [ ]:
# Any indicando el axis = 0 (en las columnas)

# Devuelve un booleano de tamaño igual al número de columnas.
column_mayor_que_80 = np.any(file_data > 80, axis = 0)# con axis es para recorrer las columnas # nos da un valor por columna

column_mayor_que_90 = np.any(file_data > 90, axis = 0)


file_data[:,column_mayor_que_80]
file_data[:,column_mayor_que_90]

array([[49, 93, 22, 65, 91, 99],
       [63, 53, 12, 45, 89, 30],
       [16, 49, 52, 98, 75, 88],
       [96, 75, 98, 70, 98, 18],
       [ 7, 30, 50, 95, 24, 43],
       [65, 50, 87, 27, 26, 29],
       [88, 89, 40, 58,  3, 88],
       [53, 13, 79,  0, 24, 38]])

In [ ]:
# Any indicando el axis= 1 (en las filas)
# Devuelve un booleano de tamaño igual al numero de filas.

filas_mayor_que_80 = np.any(file_data > 80, axis = 1)

filas_mayor_que_90 = np.any(file_data > 90, axis = 1)


file_data[filas_mayor_que_80,:]


array([[31, 49, 93, 22, 65, 91, 88, 50, 99],
       [42, 63, 53, 12, 45, 89, 28, 57, 30],
       [31, 16, 49, 52, 98, 75, 10, 70, 88],
       [ 9, 96, 75, 98, 70, 98, 77, 49, 18],
       [40,  7, 30, 50, 95, 24, 75, 28, 43],
       [22, 65, 50, 87, 27, 26, 38, 82, 29],
       [49, 88, 89, 40, 58,  3, 87, 75, 88]])

In [ ]:
# Filtrar los datos de las filas que tengan valores mayores que 80
f1 = file_data[filas_mayor_que_80,:]
# sobre ese resultado filtrar las coluumnas que tengan valores mayores que 90
col_mayores_que_90 = np.any(f1 > 90, axis= 0)
f1[:,col_mayores_que_90]

array([[49, 93, 22, 65, 91, 99],
       [63, 53, 12, 45, 89, 30],
       [16, 49, 52, 98, 75, 88],
       [96, 75, 98, 70, 98, 18],
       [ 7, 30, 50, 95, 24, 43],
       [65, 50, 87, 27, 26, 29],
       [88, 89, 40, 58,  3, 88]])

In [ ]:
# Se pueden anidar estas funciones para acotar un dato por ejemplo
mascara = np.any((file_data > 40) & (file_data < 60), axis= 1)
print(mascara)

#Seleccionar los datos que cumplen la condición
file_data[mascara,:]

[ True  True  True  True  True  True  True  True]


array([[31, 49, 93, 22, 65, 91, 88, 50, 99],
       [42, 63, 53, 12, 45, 89, 28, 57, 30],
       [31, 16, 49, 52, 98, 75, 10, 70, 88],
       [ 9, 96, 75, 98, 70, 98, 77, 49, 18],
       [40,  7, 30, 50, 95, 24, 75, 28, 43],
       [22, 65, 50, 87, 27, 26, 38, 82, 29],
       [49, 88, 89, 40, 58,  3, 87, 75, 88],
       [36, 53, 13, 79,  0, 24, 23, 79, 38]])

In [2]:
# Definimos una matriz en el que cada columna es un mes del año y cada fila es un departamento de mi empresa

departamentos = np.array(['Ventas', 'Marketing', 'RRHH', 'Compras', 'Producción'])

gastos = np.random.randint(0,10000,size=(5,12), dtype=np.int32)
print(gastos)

[[1884 7650 4866 8265 3520 6029 2362 9256 4384 8869 9981 9238]
 [7432 7735 9335 9529 2138 6364 3563 9132 5466 1005 6719 5789]
 [7337 4704 1938 3496 7476 8980 1872  294 4848 8078 6993 6342]
 [ 918 5502 2208 2810 1613 8719 5485 9090 1541 8760 5901 8727]
 [6695 6879 7245 9436 3557 5829 8351 4049 8257 8421 9424 7294]]


In [3]:
# Conocer que departamentos gastan más de 5000€ en el mes de enero
gastos[:,0] > 5000
print(departamentos[gastos[:,0] > 5000])

['Marketing' 'RRHH' 'Producción']
